script:
  - python update.py -a ${OHLOH_KEY}
after_success:
  - if [ "master" != $TRAVIS_BRANCH ]; then exit 0; fi; 
  - git config --global user.email "deploy@travis-ci.org"
  - git config --global user.name "Travis deploy"
  - git remote add github "https://${GH_TOKEN}@github.com/redecentralize/alternative-internet.git" > /dev/null
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}@github.com" > .git/credentials
  - git commit -a -m "Updating README.md with new project details"
  - git push github master > /dev/null
env:
  global:
  - secure:
